# Generated by Django 4.1.5 on 2023-03-16 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('poster_layout', models.CharField(choices=[('layout 1', 'layout 1'), ('layout 2', 'layout 2'), ('layout 3', 'layout 3'), ('layout 4', 'layout 4'), ('layout 5', 'layout 5')], default='layout 1', max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('Is_public', models.BooleanField(default=False)),
                ('Is_rsvp', models.BooleanField(default=False)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
