# Generated by Django 4.1.5 on 2023-03-06 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GuestDetails',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('Is_rsvp', models.BooleanField()),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.eventdetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='PlannedEvent',
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.userdetails'),
        ),
    ]
