# Generated by Django 4.1.5 on 2023-03-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_eventdetails_guestdetails_userdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='Is_public',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='Is_rsvp',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='GuestDetails',
        ),
    ]
