# Generated by Django 4.1.5 on 2023-03-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_eventdetails_is_public_eventdetails_is_rsvp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetails',
            name='link',
        ),
        migrations.RemoveField(
            model_name='eventdetails',
            name='u_id',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
